-- Seed demo tickets for all Comms tabs
-- Uses real user emails: soc.analyst@secops.com (GSOC), adam@ava-cyber.com (End-User)

-- ── User to SOC (User Reports) ────────────────────────────────────────────────
INSERT INTO tickets (title, text, status, priority, created_by, assigned_to, type) VALUES
('Lost company laptop', E'Hello,\nI would like to report that my company laptop is missing. I believe I may have lost it while traveling today. Please let me know what I should do next and if there are any steps needed to secure my account or the device.\n\nThank you.', 'New', 'High', 'adam@ava-cyber.com', 'soc.analyst@secops.com', 'User Report'),
('Too many MFA notifications', E'Hello,\nToday I received many MFA approval notifications on my phone even though I was not trying to log in. After many requests I accidentally approved one of them. I am not sure if this could be suspicious. Could you please check if someone tried to access my account?\n\nThank you.', 'New', 'High', 'adam@ava-cyber.com', 'soc.analyst@secops.com', 'User Report'),
('Clicked suspicious link from personal email', E'Hello,\nI accidentally clicked a link from an email in my personal mailbox while using my work computer. I realized afterward that it might have been malicious. I wanted to report it in case any action is needed.\n\nThank you.', 'New', 'High', 'eva@ava-cyber.com', 'soc.analyst@secops.com', 'User Report'),
('Received WhatsApp messages from CEO', E'Hello,\nI received messages on WhatsApp from someone claiming to be our CEO asking me to perform a task. It seemed unusual so I wanted to check if this might be a scam.\n\nThank you.', 'New', 'High', 'eva@ava-cyber.com', 'soc.analyst@secops.com', 'User Report'),
('Unknown USB device used', E'Hello,\nI found a USB drive and inserted it into my computer to see what was on it. After that my computer started showing many ads and behaving strangely. I thought it would be best to report this.\n\nThank you.', 'New', 'High', 'adam@ava-cyber.com', 'soc.analyst@secops.com', 'User Report'),
('CMD window appearing in background', E'Hello,\nI noticed a command prompt window (cmd.exe) briefly appearing in the background on my computer. I did not open it myself and I am not sure what caused it. Could you please check if this is normal?\n\nThank you.', 'New', 'Medium', 'eva@ava-cyber.com', 'soc.analyst@secops.com', 'User Report'),
('Accidentally sent sensitive file externally', E'Hello,\nI believe I accidentally sent a file containing internal information to an external partner by email. I realized it shortly after sending it and wanted to report it immediately. Please advise if any action is required.\n\nThank you.', 'New', 'Medium', 'adam@ava-cyber.com', 'soc.analyst@secops.com', 'User Report')
ON CONFLICT DO NOTHING;

-- ── SOC to User (Activity Verification + Security Announcements) ──────────────
INSERT INTO tickets (title, text, status, priority, created_by, assigned_to, type) VALUES
('Logon from suspicious location', E'Hello,\nSecurity Operations Center has detected suspicious activity related to your account/computer.\n\nWe have observed a sign-in to your work account from a new/unfamiliar location different from your primary location based on Active Directory.\nThe sign-in has happened on 08.03.24 at 20:03:45 from Bogota, Colombia, IP 98.98.26.155.\n\nPlease confirm whether you are aware of this activity, or whether you are not informed about any reason of signing-in from this location.\n\nThank you.', 'New', 'Medium', 'soc.analyst@secops.com', 'adam@ava-cyber.com', 'Activity Verification'),
('Installation of Kali Linux detected', E'Hello,\nSecurity Operations Center has detected unusual activity related to your work computer.\n\nWe have identified an installation of the Kali Linux operating system on your machine. Kali Linux is a specialized distribution commonly used for penetration testing and security research.\n\nSince this type of software is not typically required for standard business operations, we would like to verify whether this installation was authorized and required for your work activities.\n\nPlease confirm whether you initiated this installation and provide additional context regarding its purpose.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'eva@ava-cyber.com', 'Activity Verification'),
('Social engineering campaign impersonating CEO', E'Hello,\n\nWe would like to inform you that we have identified an ongoing social engineering campaign targeting our users.\n\nIn this campaign, attackers are impersonating our CEO and sending messages asking employees to contact them via a personal phone number. This is a scam attempt designed to collect information or request unauthorized actions.\n\nIf you receive such communication, please do not respond and report it immediately to the Security Operations Center.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'adam@ava-cyber.com', 'Security Announcement'),
('Compromised customer email account', E'Hello,\n\nWe would like to inform you that we have received notification that one of the email accounts belonging to your customer has been compromised.\n\nDue to the possibility of Business Email Compromise (BEC), please treat any communication received from this customer with caution.\n\nUntil further notice, please suspend financial transactions and verify any requests coming from this customer through alternative communication channels.\n\nWe will inform you once the situation has been resolved.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'eva@ava-cyber.com', 'Security Announcement')
ON CONFLICT DO NOTHING;

-- ── GRC ↔ SOC ─────────────────────────────────────────────────────────────────
INSERT INTO tickets (title, text, status, priority, created_by, assigned_to, type) VALUES
('Phishing awareness campaign notification', E'Hello SOC team,\n\nThe GRC team would like to inform you that we will be conducting a phishing awareness campaign during the upcoming period.\n\nDuring this campaign, simulated phishing emails will be sent to employees in order to evaluate and improve phishing awareness within the organization.\n\nThe emails will originate from the following sender and domains that have already been whitelisted within the environment.\n\nPlease be aware that alerts related to these emails may be triggered during the campaign period. These alerts can be considered part of the simulation.\n\nThank you for your cooperation.', 'New', 'Low', 'grc.team@secops.com', 'soc.analyst@secops.com', 'Policy Notification'),
('Unauthorized software installation detected', E'Hello GRC team,\n\nSecurity Operations Center has identified that a user installed a video game on a corporate workstation. The software appears to be unrelated to any business activities and may violate the company acceptable use policy.\n\nPlease advise whether further action or user notification is required according to current policy guidelines.\n\nThank you.', 'New', 'Medium', 'soc.analyst@secops.com', 'grc.team@secops.com', 'Policy Notification'),
('Cryptocurrency mining activity detected', E'Hello GRC team,\n\nSecurity Operations Center has detected activity on a corporate workstation consistent with cryptocurrency mining. The system appears to be running mining software that is utilizing corporate computing resources.\n\nSince this activity may violate company policies regarding acceptable use of corporate assets, we would like to inform GRC and request guidance on further action.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'grc.team@secops.com', 'Policy Notification'),
('Use of personal email for company documents', E'Hello GRC team,\n\nSecurity Operations Center observed that a user sent several internal documents from their corporate mailbox to a personal email address.\n\nWhile the intent is currently unknown, this behavior may conflict with company data handling policies. Please advise if this case should be escalated for compliance review.\n\nThank you.', 'New', 'Medium', 'soc.analyst@secops.com', 'grc.team@secops.com', 'Policy Notification')
ON CONFLICT DO NOTHING;

-- ── SOC ↔ Pentesting ──────────────────────────────────────────────────────────
INSERT INTO tickets (title, text, status, priority, created_by, assigned_to, type) VALUES
('Suspicious activity potentially related to penetration testing', E'Hello Red Team,\nSecurity Operations Center has identified activity on host HGY48i763 that appears to be related to a potential penetration testing exercise.\n\nDuring our investigation we observed several behaviors including privilege escalation attempts, persistence mechanisms, and the use of a recently created account named "Bobby Staples".\n\nDue to the nature of the activity, the affected host has been placed in quarantine. Please confirm whether this activity is part of an authorized penetration testing engagement.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'red.team@secops.com', 'Investigation'),
('Suspicious internal network scanning activity', E'Hello Red Team,\n\nSecurity Operations Center has detected unusual network scanning activity originating from host DKT55291. The host appears to be performing a large number of connection attempts to multiple internal systems across several network segments.\n\nThe behavior resembles reconnaissance activity commonly associated with penetration testing tools such as Nmap.\n\nPlease confirm whether this activity is related to any Red Team engagement.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'red.team@secops.com', 'Investigation'),
('Suspicious credential harvesting page detected', E'Hello Red Team,\n\nSecurity Operations Center has identified a suspicious internal web page hosted on server WEB7721 which appears to mimic our corporate login portal.\n\nThe page contains form fields requesting employee credentials and is accessible from the internal network. This behavior resembles a credential harvesting technique.\n\nPlease confirm whether this activity is part of any authorized Red Team engagement.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'red.team@secops.com', 'Investigation'),
('Unauthorized use of exploitation framework detected', E'Hello Red Team,\n\nSecurity Operations Center has detected activity on host FIN8821 that resembles the use of an exploitation framework. The system appears to be running processes consistent with Metasploit modules attempting lateral movement.\n\nPlease confirm if this activity is related to any ongoing penetration testing engagement.\n\nThank you.', 'New', 'Critical', 'soc.analyst@secops.com', 'red.team@secops.com', 'Investigation')
ON CONFLICT DO NOTHING;

-- ── SOC to Vulnerability Management ──────────────────────────────────────────
INSERT INTO tickets (title, text, status, priority, created_by, assigned_to, type) VALUES
('Critical vulnerability detected in Apache servers', E'Hello,\n\nSecurity Operations Center has received intelligence regarding a critical vulnerability affecting Apache HTTP Server instances (CVE-2023-25690).\n\nBased on our asset visibility, several internal servers appear to be running potentially vulnerable versions of Apache.\n\nPlease review the affected assets and apply the necessary patches or mitigation measures as soon as possible.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'vuln.mgmt@secops.com', 'Vulnerability Coordination'),
('OpenSSH vulnerability affecting Linux hosts', E'Hello,\n\nThe Security Operations Center has been informed about a newly disclosed vulnerability impacting OpenSSH services (CVE-2024-6387).\n\nOur monitoring indicates that several Linux servers in the environment may be running affected versions of OpenSSH.\n\nPlease review the impacted systems and schedule patching or mitigation as soon as possible.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'vuln.mgmt@secops.com', 'Vulnerability Coordination'),
('Microsoft Exchange vulnerability advisory', E'Hello,\n\nSecurity Operations Center has identified a newly published vulnerability affecting Microsoft Exchange servers (CVE-2023-23397).\n\nThis vulnerability may allow attackers to perform credential relay attacks and potentially gain unauthorized access.\n\nPlease review all Exchange servers and ensure the latest security updates are applied.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'vuln.mgmt@secops.com', 'Vulnerability Coordination'),
('Critical vulnerability in Fortinet VPN appliances', E'Hello,\n\nSecurity Operations Center has received threat intelligence regarding an actively exploited vulnerability affecting Fortinet VPN appliances (CVE-2023-27997).\n\nPlease review whether any Fortinet devices in the environment are running vulnerable firmware versions and prioritize patching if applicable.\n\nThank you.', 'New', 'Critical', 'soc.analyst@secops.com', 'vuln.mgmt@secops.com', 'Vulnerability Coordination'),
('VMware ESXi vulnerability requiring patching', E'Hello,\n\nSecurity Operations Center has received information regarding a vulnerability affecting VMware ESXi hypervisors (CVE-2023-20867).\n\nAs ESXi hosts are critical infrastructure components, exploitation could allow attackers to compromise virtualized environments.\n\nPlease review all ESXi hosts and ensure that the latest patches have been applied.\n\nThank you.', 'New', 'High', 'soc.analyst@secops.com', 'vuln.mgmt@secops.com', 'Vulnerability Coordination')
ON CONFLICT DO NOTHING;
