ALTER TABLE tickets ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS siem_correlated BOOLEAN DEFAULT false;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS siem_match_count INT DEFAULT 0;
