INSERT INTO siem_alerts (rule_name, severity, status, source_ip, username, hostname, description) VALUES
('Multiple Failed Logins', 'high', 'open', '10.0.1.45', 'asmith', 'WORKSTATION-03', '8 failed login attempts for asmith from 10.0.1.45 within 2 minutes — possible brute force.'),
('Outbound to Threat Intel IP', 'critical', 'open', '10.0.2.88', NULL, 'SERVER-12', 'Host 10.0.2.88 made outbound connection to known C2 IP 185.220.101.12 on port 4444.'),
('Suspicious PowerShell Execution', 'high', 'open', '10.0.3.22', 'mwilliams', 'LAPTOP-08', 'PowerShell executed with -EncodedCommand and -WindowStyle Hidden flags on LAPTOP-08.'),
('Large Data Transfer', 'critical', 'open', '10.0.4.55', 'rjones', 'WORKSTATION-11', 'User rjones transferred 1.2GB to external IP 203.0.113.99 via HTTPS in a single session.'),
('New Privileged Account Created', 'high', 'open', '10.0.0.5', 'administrator', 'DC01', 'New domain admin account SVC_BACKUP2 created outside change window on DC01.'),
('Login Outside Business Hours', 'medium', 'open', '91.108.4.55', 'bjohnson', 'VPN-GW', 'VPN login by bjohnson at 1:23 AM from unusual location (Ukraine).'),
('Lateral Movement — SMB Spread', 'critical', 'open', '10.0.5.33', NULL, 'WORKSTATION-19', 'Host 10.0.5.33 connected to 7 internal hosts via SMB within 5 minutes — possible worm or ransomware.'),
('Multiple Failed Logins', 'medium', 'open', '10.0.6.101', 'guest', 'FILESERVER-01', '12 failed login attempts on guest account from 10.0.6.101 targeting file server.'),
('Suspicious PowerShell Execution', 'critical', 'open', '10.0.7.14', 'jdoe', 'LAPTOP-14', 'PowerShell download cradle detected: IEX (New-Object Net.WebClient).DownloadString from external IP.'),
('Login Outside Business Hours', 'low', 'open', '10.0.8.77', 'contractor01', 'WORKSTATION-22', 'Contractor account logged in at 11:45 PM on a Saturday — outside normal working hours.'),
('Outbound to Threat Intel IP', 'critical', 'open', '10.0.9.200', NULL, 'SERVER-04', 'DNS beacon detected — SERVER-04 making periodic DNS queries to known malware C2 domain every 60 seconds.'),
('Large Data Transfer', 'high', 'open', '10.0.10.44', 'kthomas', 'LAPTOP-31', 'User kthomas copied 800MB to USB device — possible insider threat data exfiltration.'),
('New Privileged Account Created', 'medium', 'open', '10.0.0.8', 'helpdesk01', 'DC02', 'Helpdesk account elevated to Domain Admin group without ticket — policy violation.'),
('Lateral Movement — SMB Spread', 'high', 'open', '10.0.11.5', 'svc_scan', 'SERVER-07', 'Service account svc_scan performing port scan on internal /24 subnet — not in baseline behavior.'),
('Suspicious PowerShell Execution', 'high', 'open', '10.0.12.88', 'lwatson', 'WORKSTATION-05', 'Mimikatz-like LSASS memory read detected via PowerShell on WORKSTATION-05.'),
('Multiple Failed Logins', 'low', 'open', '10.0.13.200', 'testuser', 'WORKSTATION-44', '3 failed RDP login attempts on testuser — low threshold breach, monitor for escalation.'),
('Outbound to Threat Intel IP', 'high', 'open', '10.0.14.33', NULL, 'LAPTOP-27', 'TOR browser detected — host 10.0.14.33 connecting through TOR network from corporate device.'),
('Large Data Transfer', 'medium', 'open', '10.0.15.9', 'mlopez', 'WORKSTATION-38', 'Unusual spike in outbound email attachments — mlopez sent 47 emails with attachments in 10 minutes.'),
('Login Outside Business Hours', 'high', 'open', '185.199.108.5', 'ceo_account', 'VPN-GW', 'CEO account authenticated from unknown IP in China at 3:17 AM — high priority, possible account takeover.'),
('Lateral Movement — SMB Spread', 'medium', 'open', '10.0.16.22', 'it_admin', 'SERVER-09', 'IT admin account accessing 15 servers sequentially via RDP in 8 minutes — verify if authorized maintenance.');
